<?php

namespace App\Filament\Teacher\Widgets;

use App\Models\Exercise;
use App\Models\User;
use Filament\Widgets\ChartWidget;
use Illuminate\Support\Facades\Auth;

class StudentsOverview extends ChartWidget
{
    protected static ?string $heading = 'Students note avg par exo';

    protected static ?string $description = 'students note avg par exo for analyse students behavior';

    protected static bool $isLazy = false;

    protected static ?string $pollingInterval = "2s";

    public User $user;

    public function mount(): void
    {
        $this->user = Auth::user();
        parent::mount(); // TODO: Change the autogenerated stub

    }

    protected function getData(): array
    {
        $exercises = $this->user->exercises()
            ->orderBy('created_at')
            ->get();

        $labels = $exercises->pluck('id')->toArray();

        $points = $exercises->map(function (Exercise $exercise) {
            return $exercise->answers()->avg('note') | 0;
        })->toArray();


        return [
            'datasets' => [
                [
                    'label' => 'avg notes',
                    'data' => $points,
                ],
            ],
            'labels' => $labels
        ];
    }

    protected function getType(): string
    {
        return 'bar';
    }
}
